### ISSUE TITLE
I would like to hear your feedback

### ISSUE THREAD

**Issue by orsinium** [wizofe/PhotoPie#3]
I've noticed you're using DepHell as "glue" for your tools. I'm the author of DepHell. Is everything goes fine? I see you have no dephell in your [pyproject.toml](https://github.com/wizofe/PhotoPie/blob/master/pyproject.toml). Do you need help with dephell integration? I can make PR with DepHell's config for your project if you want :)

**Comment by wizofe** [comment]
Hi @orsinium and thanks for your comment! As I've quite a basic part of my library written (but I'm trying to make it nicer with use of classes etc) I'm looking for best practices and `dephell` seemed like a good one.

I'm very happy to accept a PR from you, especially after uploading my first working code! 

Let me update you in a few days and thanks a lot for the offer!
